---
title: 'Preprocessing: Discovery lung cancer patient cohort'
author: "Qian-Wu Liao"
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    code_folding: hide
---

<font size='4'> Description: </font>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10)
knitr::opts_knit$set(root.dir = '/Users/qianwu/Desktop/SMART-CARE_LungCancer_Discovery')
```

Load libraries
```{r load libraries, message=F}
library(readr)
library(readxl)
library(vsn)
library(limma)
library(visdat)
library(SummarizedExperiment)
library(tidyverse)
# Load user-defined functions
source('./code/analysis_pipeline.R')
```

```{r prepare global info, message=F}
# Load patient metadata
patientMetadat <- readxl::read_excel('./data/patient_metadata.xlsx')
colnames(patientMetadat) <- patientMetadat[3,]
patientMetadat <- dplyr::slice(patientMetadat, -c(1:3)) %>%
  dplyr::select(-c(Identifier, Diagnosis, Nutrition)) %>%
  dplyr::rename(Patient = Code, Age = `Age at diagnosis`, Stage = `Pathological stage`,
                Smoking = `Smoking status`, Adjuvant = `Adjuvant chemotherapy`) %>%
  dplyr::mutate(Gender = dplyr::case_when(Gender == 'MALE' ~ 'Male',
                                          Gender == 'FEMALE' ~ 'Female'),
                Smoking = dplyr::case_when(Smoking == 'SMOKER' ~ 'Smoker',
                                           Smoking == 'EX-SMOKER' ~ 'Ex-smoker',
                                           Smoking == 'NON-SMOKER' ~ 'Non-smoker'),
                Adjuvant = dplyr::case_when(Adjuvant == 'true' ~ 'True',
                                            Adjuvant == 'false' ~ 'False'),
                Metastasis = dplyr::case_when(Stage == 'IIB' ~ 'Yes',
                                              Stage != 'IIB' ~ 'No'),
                Age = as.numeric(Age))

# Load sample metadata
smpMetadat <- readxl::read_excel('./data/sample_metadata.xlsx')
colnames(smpMetadat) <- smpMetadat[3,]
smpMetadat <- dplyr::slice(smpMetadat, -c(1:3)) %>%
  dplyr::filter(`SMART-CARE cohort identifier` == 'DISCOVERY_COHORT') %>%
  dplyr::select(c(Code, Visit, `Material submitted`, `Date and time of collection or surgery`, Parents)) %>%
  dplyr::rename(Sample = Code, Status = Visit, SmpType = `Material submitted`,
                Date = `Date and time of collection or surgery`, Patient = Parents) %>%
  dplyr::mutate(Sample = stringr::str_remove_all(Sample, '^SC_DIS_S_|^SC_S_|_P'),
                Status = dplyr::case_when(Status == 'PRETHERAPEUTIC' ~ 'Baseline',
                                          Status == 'FOLLOW-UP' ~ 'Follow-up',
                                          Status == 'RECURRENCE' ~ 'Recurrence'),
                SmpType = dplyr::case_when(SmpType == 'EDTA_PLASMA' ~ 'Plasma',
                                           SmpType == 'FRESH_FROZEN_TISSUE' ~ 'Tissue'),
                Date = stringr::str_extract(Date, '\\d+-\\d+'),
                Patient = stringr::str_remove(Patient, '/THRX_SPACE/THRX_DB/')) %>%
  dplyr::arrange(Patient)

# List sample annotations to keep in SE objects
smpAnno <- c('Condition', 'Patient', 'Recurrence', 'Gender', 'Age', 'Smoking',
             'Stage', 'Adjuvant', 'Metastasis')
```

# Tissue Proteomics

```{r message=F}
# Load unprocessed data
proTissueTab <- readr::read_tsv('./data/AG_Krijgsveld/20230815_MarcS_Discovery_Tissue.pg_matrix.tsv') %>%
  dplyr::select(-c(Protein.Ids, First.Protein.Description)) %>%
  tidyr::pivot_longer(cols = -c('Protein.Group', 'Protein.Names', 'Genes'),
                      names_to = 'Sample', values_to = 'Abundance') %>%
  dplyr::mutate(Protein.Names = stringr::str_remove_all(Protein.Names, '_HUMAN'),
                Sample = stringr::str_remove_all(Sample, '^.+SC_A_|^.+SC_DIS_A_|4\\.raw$'),
                Condition = dplyr::case_when(grepl('_NG', Sample) ~ 'Normal',
                                             grepl('TU', Sample) ~ 'Tumor'),
                Patient = stringr::str_remove(Sample, '_.+$'))

# Prepare patient metadata
# Extract included patients
tissuePats <- unique(proTissueTab$Patient)
# Extract patient recurrence information
recurPats <- dplyr::filter(smpMetadat, Patient %in% tissuePats, Status == 'Recurrence') %>%
  dplyr::pull(Patient)
patientAnno <- dplyr::filter(patientMetadat, Patient %in% tissuePats) %>%
  dplyr::mutate(Recurrence = dplyr::case_when(Patient %in% recurPats ~ 'Yes',
                                              !Patient %in% recurPats ~ 'No'))
# Combine all information
proTissueTab <- dplyr::left_join(proTissueTab, patientAnno, by = 'Patient')

proTissue <- doPreprocessing(proTissueTab, feat = 'Protein.Group', smp = 'Sample',
                             val = 'Abundance', featAnno = c('Protein.Names', 'Genes'),
                             smpAnno = smpAnno, do_featFilt = T, cutoff = 0.67,
                             viz_miss = T, save_path = NULL)
```




# Plasma Proteomics

```{r}
# Load unprocessed data
proPlasmaTab <- readr::read_tsv('./data/AG_Krijgsveld/20230811_MarcS_Discovery_Plasma.pg_matrix.tsv') %>%
  dplyr::select(-c(Protein.Ids, First.Protein.Description)) %>%
  tidyr::pivot_longer(cols = -c('Protein.Group', 'Protein.Names', 'Genes'),
                      names_to = 'Sample', values_to = 'Abundance') %>%
  dplyr::mutate(Protein.Names = stringr::str_remove_all(Protein.Names, '_HUMAN'),
                Sample = stringr::str_remove_all(Sample, '^.+SC_DIS_A_|_4\\.raw$|\\.raw$|^.+KA_|_P'),
                Sample = stringr::str_replace(Sample, 'P_', '_'),
                Sample = stringr::str_remove(Sample, '^SC_A_'),
                Sample = dplyr::case_when(Sample == 'FD01075852' ~ 'R1WTOP_V1',
                                          Sample == 'FD05926483' ~ 'R1WTOP_V2',
                                          Sample == 'FD01282286' ~ 'R1WTOP_V3',
                                          Sample == 'FD07174643' ~ 'R1WTOP_V4',
                                          !Sample %in% c('FD01075852', 'FD05926483',
                                                         'FD01282286', 'FD07174643') ~ Sample),
                Sample = stringr::str_remove_all(Sample, '_FD\\d+|_LV\\d+'),
                Patient = stringr::str_remove(Sample, '_.+$'))
```

