---
title: "Analysis Reports"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Method Development cohort

Method Development cohort is defined by 20 Lung Cancer (Adenocarcinoma) patients.
At the Baseline timepoint (during the surgical treatment), Tumor and Normal Tissue
samples were collected from the patients. In addition, Plasma samples were also
collected, so-called Baseline Plasma. After around two years, Plasma samples were
collected again from these 20 patients where half of them experienced cancer recurrences.
With these samples, Proteomics, Metabolomics, and Lipidomics data was generated
by different research teams using varied methods.\

We got 12 quality datasets as follows:\
AG Hell &rarr; Targeted Tissue and Plasma Metabolomics (2)\
AG Krijgsveld &rarr; DDA and DIA Tissue and Plasma Proteomics (5)\
AG Hopf &rarr; Untargeted Tissue and Plasma Metabolomics and Lipidomics (4)\
AG Klingm端ller &rarr; DIA Tissue Proteomics (1)

The preprocessed datasets can be downloaded from openBIS (/COMPUTATIONAL_SPACE/LU/LU_DATA_1/THRX_DATA_ALL),
and the preprocessing details can be found in Section 1: Data Preprocessing.

---

### 1. Data Preprocessing
We first preprocessed all datasets stated above, which includes data cleansing,
feature filtering, and data normalization using VSN. For Untargeted Metabolomics
and Lipidomics generated by AG Hopf, due to triplicate measures of each sample,
we also (1) compared varied data normalization techniques (log2-transformation,
VSN, and median normalization), (2) conducted batch correction if needed, and (3)
merged triplicates into individual measures.

### 1.1 [Tissue and Plasma Targeted Metabolomics and DDA Proteomics](MethodDev_01_preprocessing_targeted_DDA.html)
### 1.2 [Tissue and Plasma Untargeted Metabolomics and Lipidomics](MethodDev_01_preprocessing_untargeted.html)
<!-- Feature filtering: 67% -->
### 1.3 [Tissue and Plasma DIA Proteomics (Krijgsveld & Klingm端ller)](MethodDev_01_preprocessing_DIA.html)
<!-- Feature filtering: 50% -->

---

### 2. Preliminary (Single-Omics) Analysis
We conducted univariate (t-test) and multivariate (PCA) analyses on individual
datasets to have an overview of data and take an initial look at data power in terms
of predicting patient cancer recurrence. Association between each feature (e.g.,
protein level) and cancer recurrence was tested by t-test, which captures significant
features that can separate recurrence and non-recurrence patient groups. PCA was
performed to view sources of data variance associated with certain metadata variables.
The results show that (1) Plasma Metabolomics/Lipidomics has higher signal-to-noise
ratios than that of Tissues, (2) Normal Tissue DIA Proteomics provides abundant
recurrence-related information, and (3) Baseline Plasma samples are comparable to
Follow-up Plasma samples.

### 2.1 [Tissue and Plasma Targeted Metabolomics and DDA Proteomics](MethodDev_02_soa_targeted_DDA.html)
### 2.2 [Tissue and Plasma Untargeted Metabolomics and Lipidomics](MethodDev_02_soa_untargeted.html)
<!-- Feature filtering: 67% -->
### 2.3 [Tissue and Plasma DIA Proteomics (Krijgsveld & Klingm端ller)](MethodDev_02_soa_DIA.html)
<!-- Feature filtering: 50% -->

---

### 3. Comparisons Between Datasets Generated by Different Methods
We investigated the similarity between Targeted and Untargeted Plasma/Tissue Metabolomics
generated by AG Hell and AG Hopf. *Note that Targeted Metabolomics includes both*
*metabolites and lipids.* The results reveal that Targeted and Untargeted Plasma/Tissue
metabolite features are not that correlated, which may indicate that either they
can provide complementary information or there exists technical or biological noise.
Besides, DIA/DDA Tissue/Plasma Proteomics generated by AG Krijgsveld and AG Klingm端ller
was also analyzed. <!-- Feature filtering: 67% -->

### 3.1 [Comparisons Between Targeted and Untargeted Metabolomics](comparisons_targeted_untargeted.html)
### 3.2 [Comparisons Between DIA and DDA Proteomics](comparisons_DIA_DDA.html)

---

### 4. MOFA Models
We trained several MOFA models on varied omics data combinations to observe model
performance on predicting patient cancer recurrence. The idea is that, in clinical
situations, Plasma samples are easier to collect, so we firstly built models using
only Plasma omics (Plasma Metabolomics, Lipidomics, and Proteomics), and based on
these models, we then added or removed omics to see changes in model performance.
<!-- Feature filtering: 67% -->

### 4.1 [Latest: Trained MOFA Models](mofa_models.html)
### 4.2 [Enrichment Analysis](mofa_downstream_analysis.html)

### 4.3 [Old: Trained MOFA Models](mofa_varied_omics_combinations.html)
The results show that, in general, the model trained on the combination composed
of Untargeted Plasma Metabolomics, Plasma Lipidomics, and Plasma Proteomics performs best.

---

## Discovery cohort
Discovery cohort is defined by 81 Lung Cancer patients and 17 of them were also
included in Method Development cohort. 43 patients got quality Tumor and Normal
Tissues. All patients got Plasma samples and 80 of them got Baseline Plasma samples,
where 17 Baseline Plasma samples were included in Method Development cohort.

We received 2 datasets as follows:\
AG Krijgsveld &rarr; DIA Tissue and Plasma Proteomics (2)

---

### 1. Data Preprocessing

### 1.1 [Tissue and Plasma DIA Proteomics](Discovery_01_preprocessing_DIA.html)

---

### 2. Preliminary (Single-Omics) Analysis

### 2.1 [Tissue and Plasma DIA Proteomics](Discovery_02_soa_DIA.html)

---

### 3. Cross-Cohort Analysis: [Tissue DIA Proteomics](CrossCohort_investigation.html)

